import './scrollToTop';
import './modal-footer';
import './input-search';
// import './my_library';
import './modal-movie';
import './create-movie-markup';
import './create-movie-modal-markup';
import './changeGenresToName';
import './reanderTranding';
import './localeStorage-watch&queue';